# -*- coding: utf-8 -*-
"""Extra_HA3_1_Dergunov_VA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_TKnD4KIrudWNUsOueHnivE6D9v_LQTR
"""

import threading


lock_1 = threading.Lock()
lock_2 = threading.Lock()

def first():
    while True:
        with lock_1.acquire():
            with lock_2.acquire():
                print("First")

def second():
    while True:
        with lock_1.acquire():
            with lock_2.acquire():
                print("Second")


t1 = threading.Thread(target = first)
t1.daemon = True

t2 = threading.Thread(target = second)
t2.daemon = True

t1.start()
t2.start()